[package]
name = "frugallm-app"
version = "0.0.14"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "frugallm_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies]
lazy_static = "1.4"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-shell = "2.3.6"
tauri-plugin-http = "2.6.0"
tauri-plugin-store = "2"
keyring = "4.1.6"
dotenvy = "0.15.7"
portable-pty = "0.9.0"
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "fs", "io-util", "process"] }
reqwest = { version = "0.13.4", features = ["json", "stream"] }
nvml-wrapper = "0.13.0"
sysinfo = "0.39.6"
tauri-plugin-clipboard-manager = "2"
futures-util = "0.3.34"
tauri-plugin-autostart = "2.5.1"
regex = "1"

[dev-dependencies]
tempfile = "3.10.1"
